lang: en
locale: en_US
default_color: auto

title: Yoosuf Mohamed
author: Yoosuf Mohamed
email: mayoosuf@gmail.com
description: >
  Helping startups and enterprises build AI automation and AI-first products that scale. Systems Architect specializing in LLM, RAG, Go, Elixir, FastAPI, Node, NestJS, NextJS, ReactJS, and Flutter.
baseurl: ""
url: "https://yoosuf.me"
twitter_username: aitchdei
github_username: yoosuf

twitter:
  username: aitchdei
  card: summary_large_image

social:
  name: Yoosuf Mohamed
  links:
    - https://twitter.com/aitchdei
    - https://www.facebook.com/aitchdei
    - https://www.linkedin.com/in/yoosufm
    - https://github.com/yoosuf
    - https://www.instagram.com/aitchdei/
    - https://www.youtube.com/@YoosufMo

logo: /assets/images/yoosuf.jpg
image: /assets/images/yoosuf.jpg

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/yoosuf.jpg

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

sass:
  sass_dir: _sass

google_analytics_tracking_id: G-SJQ1MBM1PF

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

exclude:
  - Gemfile
  - Gemfile.lock
