lang: en
default_color: auto

title: Yoosuf Mohamed
email: mayoosuf@gmail.com
description: >
  Yoosuf is with  decade of experience in programming, application development and maintenance. Comprehensive knowledge of Object-Oriented Design and Analysis with extensive experience in the full life cycle of the software design process including requirements definition, prototyping, proof of concepts, design, interface implementation, testing and maintenance.
baseurl: ""
url: "/"
twitter_username: aitchdie
github_username: yoosuf

sass:
  sass_dir: _sass

google_analytics_tracking_id: UA-73725836-1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
